# Global
loglevel: TRACE # One of ["TRACE", "DEBUG", "INFO", "SUCCESS", "WARNING", "ERROR", "CRITICAL"]


# Test
launchfile: run.launch
map: Town02_Opt

# Vehicle
ego_vehicle:
  type: guam
  location: 
