# Global
loglevel: TRACE # One of ["TRACE", "DEBUG", "INFO", "SUCCESS", "WARNING", "ERROR", "CRITICAL"]

# Simulation modes
# simple: run the simulator and let it run until user stops it via ctrl+c
# integer value: run simulator for value number of iterations
simulation_mode: simple

landing_threshold: 0.1 #  in meters

# Order of services here is also the order in which services are started
services:
  carla:
    include: services/carla.yml
  jaxguam:
    include: services/jaxguam.yml
  env_sim:
    include: services/env_sim.yml
  ground_station:
    include: services/ground_station.yml
  sim_control:
    include: services/sim_control.yml

# Test
map: Town02_Opt
spectator_follows_ego_vehicle: True

# Vehicle
ego_vehicle:
  include: ego_vehicle/jaxguam.yml
  debug: false
  location:
    x: 0
    y: 0
    z: 100
  velocity:
    x: 0
    y: 0
    z: 0

# Adversarial object
adv_object:
  enabled: True # One of ["True", "False"]
  pose:
    type: relative # One of ["absolute", "relative"]. If "relative", then relative to the starting pose of the ego vehicle.
    location:
      x: 0
      y: 0
      z: -20
    rotation:
      roll: 0
      pitch: 0
      yaw: 0
  velocity:
    x: 0
    y: 0
    z: 0

# Target point
target:
  type: relative # One of ["absolute", "relative"]. Absolute -- absolute in CARLA's global coordinate frame. Relative -- relative to the vehicle's starting location.
  x: 0
  y: 0
  z: -100
